version: '3.8'

services:
  app:
    # Build the Docker image using the provided Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Mount the current directory for live development
    volumes:
      - ./:/usr/src/app
      # Prevent overwriting node_modules inside the container
      - /usr/src/app/node_modules

    # Map host port 3000 to container port 3000
    ports:
      - "3000:3000"

    # Set environment variables
    environment:
      NODE_ENV: development

    # Restart policy
    restart: unless-stopped